#!/usr/bin/env python3
"""
Generate a PDF slideshow from frame images using ReportLab.
Each frame gets a full page with timestamp and description.
"""

import os
import sys
import json
import re
from pathlib import Path
from datetime import timedelta

def generate_pdf_slideshow(frames_dir: str, output_pdf: str = "frame_slideshow.pdf"):
    """Generate PDF slideshow from frame images."""
    
    try:
        from reportlab.lib.pagesizes import landscape, A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Image, Paragraph, Spacer, PageBreak
        from reportlab.lib.units import inch
    except ImportError:
        print("Error: reportlab not installed. Install with: pip install reportlab")
        sys.exit(1)
    
    frames_path = Path(frames_dir)
    if not frames_path.exists():
        print(f"Error: Frames directory not found: {frames_dir}")
        sys.exit(1)
    
    # Find all jpg files
    frame_files = sorted(frames_path.glob("*.jpg"))
    if not frame_files:
        print(f"Error: No .jpg files found in {frames_dir}")
        sys.exit(1)
    
    print(f"📊 Found {len(frame_files)} frames")
    
    # Try to load frame_report.json for descriptions (optional)
    report_path = frames_path / "frame_report.json"
    frame_reports = {}
    if report_path.exists():
        with open(report_path) as f:
            report = json.load(f)
        frames_list = report.get("frames", []) if isinstance(report, dict) else report
        for frame in frames_list:
            path = frame.get("frame_path") or frame.get("path", "")
            if path:
                frame_reports[Path(path).name] = frame
    
    # Build frame data
    frame_data = []
    for i, frame_path in enumerate(frame_files):
        name = frame_path.stem
        timestamp = 0
        description = f"Frame {i+1}"
        
        # Try to extract timestamp from filename
        match = re.search(r'_(\d+)s_', name)
        if match:
            timestamp = int(match.group(1))
        
        # Try to extract description from filename
        parts = name.split('_')
        if len(parts) > 3:
            description = ' '.join(parts[3:]).replace('_', ' ').title()
        
        # Check if we have report data for this frame
        bugs = []
        if frame_path.name in frame_reports:
            report_frame = frame_reports[frame_path.name]
            bugs = report_frame.get("bugs", [])
            if "notes" in report_frame:
                description = report_frame["notes"]
        
        ts_formatted = str(timedelta(seconds=timestamp))
        
        frame_data.append({
            "index": i,
            "timestamp": ts_formatted,
            "timestamp_raw": timestamp,
            "description": description,
            "path": str(frame_path),
            "bugs": bugs
        })
    
    # Create PDF
    output_path = frames_path / output_pdf
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=landscape(A4),
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#667eea'),
        spaceAfter=12
    )
    timestamp_style = ParagraphStyle(
        'Timestamp',
        parent=styles['Normal'],
        fontSize=14,
        textColor=colors.HexColor('#764ba2'),
        fontName='Helvetica-Bold',
        spaceAfter=6
    )
    desc_style = ParagraphStyle(
        'Description',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.gray,
        spaceAfter=12
    )
    bug_style = ParagraphStyle(
        'Bug',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.red,
        leftMargin=12,
        spaceAfter=6
    )
    
    story = []
    
    # Title page
    story.append(Paragraph("🎬 VaultGate Pitch — Frame Review", title_style))
    story.append(Paragraph(f"Video: VaultGatePitch.mp4 (v16)", styles['Normal']))
    story.append(Paragraph(f"Total Frames: {len(frame_data)}", styles['Normal']))
    story.append(Paragraph("Use arrow keys or swipe to navigate in PDF viewer", desc_style))
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("Generated by frame_review.py + generate_pdf_slideshow.py", styles['Normal']))
    story.append(PageBreak())
    
    # Frame pages
    for frame in frame_data:
        # Timestamp header
        story.append(Paragraph(f"⏱️  {frame['timestamp']} — {frame['description']}", timestamp_style))
        
        # Frame image (scaled to fit page)
        # A4 landscape: 11.69 x 8.27 inches, minus margins = ~10.7 x 7.3 inches
        # 16:9 aspect ratio, so max width at 7.3 height = 12.97 inches (too wide)
        # Use 9.5 inches width, height = 5.34 inches
        img = Image(frame['path'], width=9.5*inch, height=5.34*inch)
        story.append(img)
        
        story.append(Spacer(1, 0.2*inch))
        
        # Bug report if any
        if frame['bugs'] and len(frame['bugs']) > 0:
            story.append(Paragraph("🐛 Detected Issues:", ParagraphStyle('BugTitle', parent=styles['Heading3'], fontSize=12, spaceAfter=6)))
            for bug in frame['bugs']:
                severity_color = colors.red if bug.get('severity') == 'CRITICAL' else colors.orange if bug.get('severity') == 'WARNING' else colors.blue
                bug_text = f"[{bug.get('severity', 'INFO')}] {bug.get('type', 'Unknown')}: {bug.get('description', 'No description')}"
                story.append(Paragraph(bug_text, bug_style))
        
        story.append(PageBreak())
    
    # Build PDF
    doc.build(story)
    
    print(f"✅ PDF generated: {output_path}")
    print(f"📄 Pages: {len(frame_data) + 1} (title + {len(frame_data)} frames)")
    print(f"📁 Open with: open {output_path}")
    
    return str(output_path)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 generate_pdf_slideshow.py <frames_directory>")
        print("Example: python3 generate_pdf_slideshow.py /data/.openclaw/workspace/vaultgate/frames")
        sys.exit(1)
    
    generate_pdf_slideshow(sys.argv[1])
